# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_testic.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_testWidget(object):
    def setupUi(self, testWidget):
        testWidget.setObjectName(_fromUtf8("testWidget"))
        testWidget.setWindowModality(QtCore.Qt.NonModal)
        testWidget.resize(726, 594)
        testWidget.setMinimumSize(QtCore.QSize(0, 0))
        testWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget = QtGui.QWidget(testWidget)
        self.widget.setGeometry(QtCore.QRect(160, 70, 551, 501))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.widget)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 531, 499))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidgetIspisIzBaze = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetIspisIzBaze.sizePolicy().hasHeightForWidth())
        self.tableWidgetIspisIzBaze.setSizePolicy(sizePolicy)
        self.tableWidgetIspisIzBaze.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidgetIspisIzBaze.setMaximumSize(QtCore.QSize(517, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tableWidgetIspisIzBaze.setFont(font)
        self.tableWidgetIspisIzBaze.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidgetIspisIzBaze.setLineWidth(1)
        self.tableWidgetIspisIzBaze.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetIspisIzBaze.setAutoScrollMargin(16)
        self.tableWidgetIspisIzBaze.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidgetIspisIzBaze.setAlternatingRowColors(True)
        self.tableWidgetIspisIzBaze.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidgetIspisIzBaze.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetIspisIzBaze.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidgetIspisIzBaze.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.tableWidgetIspisIzBaze.setShowGrid(False)
        self.tableWidgetIspisIzBaze.setWordWrap(True)
        self.tableWidgetIspisIzBaze.setObjectName(_fromUtf8("tableWidgetIspisIzBaze"))
        self.tableWidgetIspisIzBaze.setColumnCount(5)
        self.tableWidgetIspisIzBaze.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetIspisIzBaze.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetIspisIzBaze.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetIspisIzBaze.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetIspisIzBaze.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetIspisIzBaze.setHorizontalHeaderItem(4, item)
        self.tableWidgetIspisIzBaze.horizontalHeader().setVisible(True)
        self.tableWidgetIspisIzBaze.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetIspisIzBaze.horizontalHeader().setDefaultSectionSize(103)
        self.tableWidgetIspisIzBaze.horizontalHeader().setHighlightSections(False)
        self.tableWidgetIspisIzBaze.horizontalHeader().setMinimumSectionSize(33)
        self.tableWidgetIspisIzBaze.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetIspisIzBaze.verticalHeader().setVisible(False)
        self.tableWidgetIspisIzBaze.verticalHeader().setDefaultSectionSize(30)
        self.tableWidgetIspisIzBaze.verticalHeader().setHighlightSections(False)
        self.verticalLayout_2.addWidget(self.tableWidgetIspisIzBaze)
        self.pushButtonSelektovano = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonSelektovano.setObjectName(_fromUtf8("pushButtonSelektovano"))
        self.verticalLayout_2.addWidget(self.pushButtonSelektovano)
        self.pushButtonRefresh = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.verticalLayout_2.addWidget(self.pushButtonRefresh)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(testWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 30, 331, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.gridLayoutWidget = QtGui.QWidget(testWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 69, 143, 301))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.labelBrojTiketaMjesec = QtGui.QLabel(self.gridLayoutWidget)
        self.labelBrojTiketaMjesec.setObjectName(_fromUtf8("labelBrojTiketaMjesec"))
        self.gridLayout_7.addWidget(self.labelBrojTiketaMjesec, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 1, 0, 1, 1)
        self.labelBrojTiketaDanas = QtGui.QLabel(self.gridLayoutWidget)
        self.labelBrojTiketaDanas.setObjectName(_fromUtf8("labelBrojTiketaDanas"))
        self.gridLayout_7.addWidget(self.labelBrojTiketaDanas, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 2, 0, 1, 1)
        self.labelSrednjaVrijednostDuzine = QtGui.QLabel(self.gridLayoutWidget)
        self.labelSrednjaVrijednostDuzine.setObjectName(_fromUtf8("labelSrednjaVrijednostDuzine"))
        self.gridLayout_7.addWidget(self.labelSrednjaVrijednostDuzine, 2, 1, 1, 1)

        self.retranslateUi(testWidget)
        QtCore.QMetaObject.connectSlotsByName(testWidget)

    def retranslateUi(self, testWidget):
        testWidget.setWindowTitle(_translate("testWidget", "Form", None))
        self.tableWidgetIspisIzBaze.setSortingEnabled(True)
        item = self.tableWidgetIspisIzBaze.horizontalHeaderItem(0)
        item.setText(_translate("testWidget", "ID", None))
        item = self.tableWidgetIspisIzBaze.horizontalHeaderItem(1)
        item.setText(_translate("testWidget", "Ticket number", None))
        item = self.tableWidgetIspisIzBaze.horizontalHeaderItem(2)
        item.setText(_translate("testWidget", "Severity", None))
        item = self.tableWidgetIspisIzBaze.horizontalHeaderItem(3)
        item.setText(_translate("testWidget", "Status", None))
        item = self.tableWidgetIspisIzBaze.horizontalHeaderItem(4)
        item.setText(_translate("testWidget", "Date", None))
        self.pushButtonSelektovano.setText(_translate("testWidget", "SELECT", None))
        self.pushButtonRefresh.setText(_translate("testWidget", "REFRESH", None))
        self.pushButton.setText(_translate("testWidget", "Search", None))
        self.labelBrojTiketaMjesec.setText(_translate("testWidget", "TextLabel", None))
        self.label_3.setText(_translate("testWidget", "Mjesec:", None))
        self.labelBrojTiketaDanas.setText(_translate("testWidget", "TextLabel", None))
        self.label.setText(_translate("testWidget", "Danas:", None))
        self.label_2.setText(_translate("testWidget", "Srednja vrijednost", None))
        self.labelSrednjaVrijednostDuzine.setText(_translate("testWidget", "TextLabel", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    testWidget = QtGui.QWidget()
    ui = Ui_testWidget()
    ui.setupUi(testWidget)
    testWidget.show()
    sys.exit(app.exec_())

