# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_selektovani.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_selektovaniId(object):
    def setupUi(self, selektovaniId):
        selektovaniId.setObjectName(_fromUtf8("selektovaniId"))
        selektovaniId.resize(900, 600)
        selektovaniId.setMinimumSize(QtCore.QSize(900, 563))
        selektovaniId.setMaximumSize(QtCore.QSize(1080, 700))
        self.gridLayout_3 = QtGui.QGridLayout(selektovaniId)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_20 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 1, 1, 1, 1)
        self.line_3 = QtGui.QFrame(selektovaniId)
        self.line_3.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 6, 2, 1, 1)
        self.line_18 = QtGui.QFrame(selektovaniId)
        self.line_18.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_18.setFrameShadow(QtGui.QFrame.Plain)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_2.addWidget(self.line_18, 0, 2, 1, 1)
        self.line = QtGui.QFrame(selektovaniId)
        self.line.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 2, 2, 1, 1)
        self.line_16 = QtGui.QFrame(selektovaniId)
        self.line_16.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_16.setFrameShadow(QtGui.QFrame.Plain)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_2.addWidget(self.line_16, 10, 2, 1, 1)
        self.line_17 = QtGui.QFrame(selektovaniId)
        self.line_17.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_17.setFrameShadow(QtGui.QFrame.Plain)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout_2.addWidget(self.line_17, 14, 2, 1, 1)
        self.line_15 = QtGui.QFrame(selektovaniId)
        self.line_15.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_15.setFrameShadow(QtGui.QFrame.Plain)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_2.addWidget(self.line_15, 8, 2, 1, 1)
        self.line_2 = QtGui.QFrame(selektovaniId)
        self.line_2.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 4, 2, 1, 1)
        self.line_5 = QtGui.QFrame(selektovaniId)
        self.line_5.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_2.addWidget(self.line_5, 10, 1, 1, 1)
        self.line_7 = QtGui.QFrame(selektovaniId)
        self.line_7.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 6, 1, 1, 1)
        self.labelWhenDidItStop = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelWhenDidItStop.setFont(font)
        self.labelWhenDidItStop.setObjectName(_fromUtf8("labelWhenDidItStop"))
        self.gridLayout_2.addWidget(self.labelWhenDidItStop, 5, 2, 1, 1)
        self.labelChangesMade = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelChangesMade.setFont(font)
        self.labelChangesMade.setObjectName(_fromUtf8("labelChangesMade"))
        self.gridLayout_2.addWidget(self.labelChangesMade, 7, 2, 1, 1)
        self.labelHowManyTermLoc = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHowManyTermLoc.setFont(font)
        self.labelHowManyTermLoc.setObjectName(_fromUtf8("labelHowManyTermLoc"))
        self.gridLayout_2.addWidget(self.labelHowManyTermLoc, 9, 2, 1, 1)
        self.labelDidItEverWork = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDidItEverWork.setFont(font)
        self.labelDidItEverWork.setObjectName(_fromUtf8("labelDidItEverWork"))
        self.gridLayout_2.addWidget(self.labelDidItEverWork, 3, 2, 1, 1)
        self.label_27 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_2.addWidget(self.label_27, 11, 1, 1, 1)
        self.label_31 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_2.addWidget(self.label_31, 19, 1, 1, 1)
        self.label_22 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_2.addWidget(self.label_22, 3, 1, 1, 1)
        self.label_26 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_2.addWidget(self.label_26, 9, 1, 1, 1)
        self.labelHasSiteEverCalled = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHasSiteEverCalled.setFont(font)
        self.labelHasSiteEverCalled.setObjectName(_fromUtf8("labelHasSiteEverCalled"))
        self.gridLayout_2.addWidget(self.labelHasSiteEverCalled, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 13, 1, 1, 1)
        self.label_24 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 5, 1, 1, 1)
        self.label_29 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 15, 1, 1, 1)
        self.labelHowManyTermDown = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelHowManyTermDown.setFont(font)
        self.labelHowManyTermDown.setObjectName(_fromUtf8("labelHowManyTermDown"))
        self.gridLayout_2.addWidget(self.labelHowManyTermDown, 11, 2, 1, 1)
        self.labelAreAnySpecTerm = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAreAnySpecTerm.setFont(font)
        self.labelAreAnySpecTerm.setObjectName(_fromUtf8("labelAreAnySpecTerm"))
        self.gridLayout_2.addWidget(self.labelAreAnySpecTerm, 13, 2, 1, 1)
        self.labelScreenShotsAttached = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScreenShotsAttached.setFont(font)
        self.labelScreenShotsAttached.setObjectName(_fromUtf8("labelScreenShotsAttached"))
        self.gridLayout_2.addWidget(self.labelScreenShotsAttached, 15, 2, 1, 1)
        self.labelModelSerialNum = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModelSerialNum.setFont(font)
        self.labelModelSerialNum.setObjectName(_fromUtf8("labelModelSerialNum"))
        self.gridLayout_2.addWidget(self.labelModelSerialNum, 17, 2, 1, 1)
        self.labelAlternativeMethod = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAlternativeMethod.setFont(font)
        self.labelAlternativeMethod.setObjectName(_fromUtf8("labelAlternativeMethod"))
        self.gridLayout_2.addWidget(self.labelAlternativeMethod, 19, 2, 1, 1)
        self.label_30 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_2.addWidget(self.label_30, 17, 1, 1, 1)
        self.label_25 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 7, 1, 1, 1)
        self.line_8 = QtGui.QFrame(selektovaniId)
        self.line_8.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_8.setFrameShadow(QtGui.QFrame.Plain)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_2.addWidget(self.line_8, 4, 1, 1, 1)
        self.line_9 = QtGui.QFrame(selektovaniId)
        self.line_9.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_9.setFrameShadow(QtGui.QFrame.Plain)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_2.addWidget(self.line_9, 2, 1, 1, 1)
        self.line_10 = QtGui.QFrame(selektovaniId)
        self.line_10.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_10.setFrameShadow(QtGui.QFrame.Plain)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_2.addWidget(self.line_10, 14, 1, 1, 1)
        self.line_4 = QtGui.QFrame(selektovaniId)
        self.line_4.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 12, 1, 1, 1)
        self.line_6 = QtGui.QFrame(selektovaniId)
        self.line_6.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_6.setFrameShadow(QtGui.QFrame.Plain)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_2.addWidget(self.line_6, 8, 1, 1, 1)
        self.line_13 = QtGui.QFrame(selektovaniId)
        self.line_13.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_13.setFrameShadow(QtGui.QFrame.Plain)
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_2.addWidget(self.line_13, 0, 1, 1, 1)
        self.line_12 = QtGui.QFrame(selektovaniId)
        self.line_12.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_12.setFrameShadow(QtGui.QFrame.Plain)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_2.addWidget(self.line_12, 20, 1, 1, 1)
        self.line_11 = QtGui.QFrame(selektovaniId)
        self.line_11.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_11.setFrameShadow(QtGui.QFrame.Plain)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_2.addWidget(self.line_11, 18, 1, 1, 1)
        self.line_14 = QtGui.QFrame(selektovaniId)
        self.line_14.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_14.setFrameShadow(QtGui.QFrame.Plain)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_2.addWidget(self.line_14, 12, 2, 1, 1)
        self.line_19 = QtGui.QFrame(selektovaniId)
        self.line_19.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_19.setFrameShadow(QtGui.QFrame.Plain)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout_2.addWidget(self.line_19, 16, 1, 1, 1)
        self.line_20 = QtGui.QFrame(selektovaniId)
        self.line_20.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_20.setFrameShadow(QtGui.QFrame.Plain)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout_2.addWidget(self.line_20, 16, 2, 1, 1)
        self.line_21 = QtGui.QFrame(selektovaniId)
        self.line_21.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_21.setFrameShadow(QtGui.QFrame.Plain)
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_2.addWidget(self.line_21, 18, 2, 1, 1)
        self.line_22 = QtGui.QFrame(selektovaniId)
        self.line_22.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_22.setFrameShadow(QtGui.QFrame.Plain)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.gridLayout_2.addWidget(self.line_22, 20, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 2, 2, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_14 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.labelDescription = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDescription.setFont(font)
        self.labelDescription.setFrameShape(QtGui.QFrame.Panel)
        self.labelDescription.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelDescription.setLineWidth(2)
        self.labelDescription.setObjectName(_fromUtf8("labelDescription"))
        self.verticalLayout_4.addWidget(self.labelDescription)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem)
        self.label123 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label123.setFont(font)
        self.label123.setAlignment(QtCore.Qt.AlignCenter)
        self.label123.setObjectName(_fromUtf8("label123"))
        self.verticalLayout_4.addWidget(self.label123)
        self.labelTroubleshooting = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTroubleshooting.setFont(font)
        self.labelTroubleshooting.setFrameShape(QtGui.QFrame.Panel)
        self.labelTroubleshooting.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelTroubleshooting.setLineWidth(2)
        self.labelTroubleshooting.setObjectName(_fromUtf8("labelTroubleshooting"))
        self.verticalLayout_4.addWidget(self.labelTroubleshooting)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.labelnexttt = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelnexttt.setFont(font)
        self.labelnexttt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelnexttt.setObjectName(_fromUtf8("labelnexttt"))
        self.verticalLayout_4.addWidget(self.labelnexttt)
        self.labelNextSteps = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNextSteps.setFont(font)
        self.labelNextSteps.setFrameShape(QtGui.QFrame.Panel)
        self.labelNextSteps.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelNextSteps.setLineWidth(2)
        self.labelNextSteps.setObjectName(_fromUtf8("labelNextSteps"))
        self.verticalLayout_4.addWidget(self.labelNextSteps)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 3, 1, 2, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelZipCode = QtGui.QLabel(selektovaniId)
        self.labelZipCode.setObjectName(_fromUtf8("labelZipCode"))
        self.horizontalLayout_4.addWidget(self.labelZipCode)
        self.labelSeverity = QtGui.QLabel(selektovaniId)
        self.labelSeverity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSeverity.setObjectName(_fromUtf8("labelSeverity"))
        self.horizontalLayout_4.addWidget(self.labelSeverity)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.labelStatus = QtGui.QLabel(selektovaniId)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStatus.sizePolicy().hasHeightForWidth())
        self.labelStatus.setSizePolicy(sizePolicy)
        self.labelStatus.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelStatus.setFont(font)
        self.labelStatus.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0.0170455, x2:1, y2:0, stop:0 rgba(99, 153, 117, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.labelStatus.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.verticalLayout_6.addWidget(self.labelStatus)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 6, 0, 1, 3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.labelContactPhone = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelContactPhone.setFont(font)
        self.labelContactPhone.setAlignment(QtCore.Qt.AlignCenter)
        self.labelContactPhone.setObjectName(_fromUtf8("labelContactPhone"))
        self.gridLayout.addWidget(self.labelContactPhone, 2, 1, 1, 1)
        self.labelSiteKey = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSiteKey.setFont(font)
        self.labelSiteKey.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSiteKey.setObjectName(_fromUtf8("labelSiteKey"))
        self.gridLayout.addWidget(self.labelSiteKey, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.labelNameLastName = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNameLastName.setFont(font)
        self.labelNameLastName.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNameLastName.setObjectName(_fromUtf8("labelNameLastName"))
        self.gridLayout.addWidget(self.labelNameLastName, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.labelContactEmail = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelContactEmail.setFont(font)
        self.labelContactEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.labelContactEmail.setObjectName(_fromUtf8("labelContactEmail"))
        self.gridLayout.addWidget(self.labelContactEmail, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelVrijeme = QtGui.QLabel(selektovaniId)
        self.labelVrijeme.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelVrijeme.setObjectName(_fromUtf8("labelVrijeme"))
        self.horizontalLayout_3.addWidget(self.labelVrijeme)
        self.labelIncidentNumber = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelIncidentNumber.setFont(font)
        self.labelIncidentNumber.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelIncidentNumber.setObjectName(_fromUtf8("labelIncidentNumber"))
        self.horizontalLayout_3.addWidget(self.labelIncidentNumber)
        self.labelDatum = QtGui.QLabel(selektovaniId)
        self.labelDatum.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.labelDatum.setObjectName(_fromUtf8("labelDatum"))
        self.horizontalLayout_3.addWidget(self.labelDatum)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.labelVersions = QtGui.QLabel(selektovaniId)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelVersions.setFont(font)
        self.labelVersions.setObjectName(_fromUtf8("labelVersions"))
        self.horizontalLayout_5.addWidget(self.labelVersions)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.line_23 = QtGui.QFrame(selektovaniId)
        self.line_23.setStyleSheet(_fromUtf8("color: rgb(129, 255, 148);"))
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.gridLayout_3.addWidget(self.line_23, 1, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 5, 0, 1, 1)

        self.retranslateUi(selektovaniId)
        QtCore.QMetaObject.connectSlotsByName(selektovaniId)

    def retranslateUi(self, selektovaniId):
        selektovaniId.setWindowTitle(_translate("selektovaniId", "Form", None))
        self.label_20.setText(_translate("selektovaniId", "<html><head/><body><p>Has site ever called support<br/>for the same issue?:</p></body></html>", None))
        self.labelWhenDidItStop.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelChangesMade.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelHowManyTermLoc.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelDidItEverWork.setText(_translate("selektovaniId", "TextLabel", None))
        self.label_27.setText(_translate("selektovaniId", "How many terminals are down:", None))
        self.label_31.setText(_translate("selektovaniId", "<html><head/><body><p>Alternative method that will<br/>be used by the site:</p></body></html>", None))
        self.label_22.setText(_translate("selektovaniId", "Did it ever work?:", None))
        self.label_26.setText(_translate("selektovaniId", "How many terminals on location:", None))
        self.labelHasSiteEverCalled.setText(_translate("selektovaniId", "TextLabel", None))
        self.label_28.setText(_translate("selektovaniId", "<html><head/><body><p>Are any of the affected terminals<br/>specialty terminals?:</p></body></html>", None))
        self.label_24.setText(_translate("selektovaniId", "When did it stop working:", None))
        self.label_29.setText(_translate("selektovaniId", "<html><head/><body><p>Screen shots attached<br/>(if applicable):</p></body></html>", None))
        self.labelHowManyTermDown.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelAreAnySpecTerm.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelScreenShotsAttached.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelModelSerialNum.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelAlternativeMethod.setText(_translate("selektovaniId", "TextLabel", None))
        self.label_30.setText(_translate("selektovaniId", "<html><head/><body><p>Model &amp; S/N <br/>(if hardware related):</p></body></html>", None))
        self.label_25.setText(_translate("selektovaniId", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Changes made around<br />that time:</p></body></html>", None))
        self.label_14.setText(_translate("selektovaniId", "Description of the Problem:", None))
        self.labelDescription.setText(_translate("selektovaniId", "<html><head/><body><p>TextLabel</p></body></html>", None))
        self.label123.setText(_translate("selektovaniId", "<html><head/><body><p>Reproduction and Troubleshooting steps<br/>taken to resolve:</p></body></html>", None))
        self.labelTroubleshooting.setText(_translate("selektovaniId", "<html><head/><body><p>TextLabel</p><p>asdasdasd</p><p>sadasdas</p><p><br/></p></body></html>", None))
        self.labelnexttt.setText(_translate("selektovaniId", "***Next Steps for next contact:", None))
        self.labelNextSteps.setText(_translate("selektovaniId", "<html><head/><body><p>TextLabel<br/>dasdasd<br/>Asdasdas</p></body></html>", None))
        self.labelZipCode.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelSeverity.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelStatus.setText(_translate("selektovaniId", "Closed", None))
        self.label_6.setText(_translate("selektovaniId", "Site/Tree/Key #:", None))
        self.labelContactPhone.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelSiteKey.setText(_translate("selektovaniId", "TextLabel", None))
        self.label_8.setText(_translate("selektovaniId", "Point of Contact:", None))
        self.labelNameLastName.setText(_translate("selektovaniId", "TextLabel", None))
        self.label_10.setText(_translate("selektovaniId", "Site/Point of Contact Phone:", None))
        self.label_12.setText(_translate("selektovaniId", "Site/Point of Contact Email:", None))
        self.labelContactEmail.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelVrijeme.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelIncidentNumber.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelDatum.setText(_translate("selektovaniId", "TextLabel", None))
        self.labelVersions.setText(_translate("selektovaniId", "<html><head/><body><p>TextLabel<br/>sadas<br/>aadas<br/>dasd</p></body></html>", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    selektovaniId = QtGui.QWidget()
    ui = Ui_selektovaniId()
    ui.setupUi(selektovaniId)
    selektovaniId.show()
    sys.exit(app.exec_())

