# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_glavni.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(967, 838)
        MainWindow.setMinimumSize(QtCore.QSize(950, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Desktop/saki.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pushButtonClearAllFields = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClearAllFields.sizePolicy().hasHeightForWidth())
        self.pushButtonClearAllFields.setSizePolicy(sizePolicy)
        self.pushButtonClearAllFields.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonClearAllFields.setFont(font)
        self.pushButtonClearAllFields.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonClearAllFields.setStyleSheet(_fromUtf8("QPushButton:hover {background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0.988636, y2:0.983, stop:0 rgba(96, 255, 170, 255), stop:0.664773 rgba(255, 255, 255, 255));}\n"
"QPushButton:pressed { border-bottom: 1px solid rgb(96, 255, 170); border-top: 1px solid white;}\n"
"QPushButton { background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(96, 255, 170, 255), stop:0.664773 rgba(255, 255, 255, 255)); border-radius: 20px; }\n"
"\n"
""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/002-dustbin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClearAllFields.setIcon(icon1)
        self.pushButtonClearAllFields.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonClearAllFields.setShortcut(_fromUtf8(""))
        self.pushButtonClearAllFields.setCheckable(False)
        self.pushButtonClearAllFields.setAutoRepeat(False)
        self.pushButtonClearAllFields.setAutoExclusive(False)
        self.pushButtonClearAllFields.setAutoRepeatDelay(300)
        self.pushButtonClearAllFields.setAutoDefault(False)
        self.pushButtonClearAllFields.setDefault(False)
        self.pushButtonClearAllFields.setFlat(False)
        self.pushButtonClearAllFields.setObjectName(_fromUtf8("pushButtonClearAllFields"))
        self.horizontalLayout_10.addWidget(self.pushButtonClearAllFields)
        spacerItem1 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.pushButtonCopyToClipboard = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCopyToClipboard.sizePolicy().hasHeightForWidth())
        self.pushButtonCopyToClipboard.setSizePolicy(sizePolicy)
        self.pushButtonCopyToClipboard.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonCopyToClipboard.setFont(font)
        self.pushButtonCopyToClipboard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonCopyToClipboard.setStyleSheet(_fromUtf8("QPushButton:hover {background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0.988636, y2:0.983, stop:0 rgba(96, 255, 170, 255), stop:0.664773 rgba(255, 255, 255, 255));}\n"
"QPushButton:pressed { border-bottom: 1px solid rgb(96, 255, 170); border-top: 1px solid white;}\n"
"QPushButton { background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(96, 255, 170, 255), stop:0.664773 rgba(255, 255, 255, 255)); border-radius: 20px; }\n"
"QPushButton:disabled {background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(96, 255, 170, 100), stop:0.664773 rgba(255, 255, 255, 100))}\n"
"\n"
""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/005-copy-1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCopyToClipboard.setIcon(icon2)
        self.pushButtonCopyToClipboard.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonCopyToClipboard.setShortcut(_fromUtf8(""))
        self.pushButtonCopyToClipboard.setCheckable(False)
        self.pushButtonCopyToClipboard.setAutoDefault(False)
        self.pushButtonCopyToClipboard.setDefault(False)
        self.pushButtonCopyToClipboard.setFlat(False)
        self.pushButtonCopyToClipboard.setObjectName(_fromUtf8("pushButtonCopyToClipboard"))
        self.horizontalLayout_10.addWidget(self.pushButtonCopyToClipboard)
        spacerItem2 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 2, 1, 1, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelTimer = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelTimer.setFont(font)
        self.labelTimer.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTimer.setObjectName(_fromUtf8("labelTimer"))
        self.gridLayout_2.addWidget(self.labelTimer, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonStart = QtGui.QPushButton(self.centralwidget)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonStart.setFont(font)
        self.pushButtonStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonStart.setStyleSheet(_fromUtf8("QPushButton {background-color: rgba(96, 255, 170, 20); border-radius: 5px}\n"
"QPushButton:checked {border: 1px solid black;}\n"
"QPushButton:hover {background-color: rgba(96, 255, 170, 120);}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/002-play-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/001-pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButtonStart.setIcon(icon3)
        self.pushButtonStart.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonStart.setCheckable(True)
        self.pushButtonStart.setChecked(False)
        self.pushButtonStart.setAutoRepeat(False)
        self.pushButtonStart.setAutoExclusive(False)
        self.pushButtonStart.setAutoDefault(False)
        self.pushButtonStart.setDefault(False)
        self.pushButtonStart.setFlat(False)
        self.pushButtonStart.setObjectName(_fromUtf8("pushButtonStart"))
        self.horizontalLayout_3.addWidget(self.pushButtonStart)
        self.pushButtonReset = QtGui.QPushButton(self.centralwidget)
        self.pushButtonReset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonReset.setFont(font)
        self.pushButtonReset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonReset.setStyleSheet(_fromUtf8("QPushButton {background-color: rgba(96, 255, 170, 20); border-radius: 5px}\n"
"QPushButton:pressed {border: 1px solid black;}\n"
"QPushButton:hover {background-color: rgba(96, 255, 170, 120);}"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/001-replay.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonReset.setIcon(icon4)
        self.pushButtonReset.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonReset.setCheckable(False)
        self.pushButtonReset.setAutoDefault(True)
        self.pushButtonReset.setDefault(False)
        self.pushButtonReset.setFlat(True)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.horizontalLayout_3.addWidget(self.pushButtonReset)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 10)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(330, 16777215))
        self.scrollArea.setFrameShape(QtGui.QFrame.Box)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, -344, 1223, 890))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_5.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_5.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 434, 982))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(15, 10, 5, 5)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_30 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setTextFormat(QtCore.Qt.AutoText)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_6.addWidget(self.label_30)
        self.plainTextEditVersions = QtGui.QPlainTextEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditVersions.sizePolicy().hasHeightForWidth())
        self.plainTextEditVersions.setSizePolicy(sizePolicy)
        self.plainTextEditVersions.setMinimumSize(QtCore.QSize(25, 80))
        self.plainTextEditVersions.setMaximumSize(QtCore.QSize(280, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEditVersions.setFont(font)
        self.plainTextEditVersions.setObjectName(_fromUtf8("plainTextEditVersions"))
        self.verticalLayout_6.addWidget(self.plainTextEditVersions)
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_6.addWidget(self.label_19)
        self.lineEditHasSiteEverCalled = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditHasSiteEverCalled.sizePolicy().hasHeightForWidth())
        self.lineEditHasSiteEverCalled.setSizePolicy(sizePolicy)
        self.lineEditHasSiteEverCalled.setMaximumSize(QtCore.QSize(280, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditHasSiteEverCalled.setFont(font)
        self.lineEditHasSiteEverCalled.setObjectName(_fromUtf8("lineEditHasSiteEverCalled"))
        self.verticalLayout_6.addWidget(self.lineEditHasSiteEverCalled)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_6.addWidget(self.label_20)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButtonNaDidItEverWork = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaDidItEverWork.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaDidItEverWork.setFont(font)
        self.pushButtonNaDidItEverWork.setObjectName(_fromUtf8("pushButtonNaDidItEverWork"))
        self.horizontalLayout_5.addWidget(self.pushButtonNaDidItEverWork)
        self.lineEditDidItEverWork = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditDidItEverWork.setFont(font)
        self.lineEditDidItEverWork.setObjectName(_fromUtf8("lineEditDidItEverWork"))
        self.horizontalLayout_5.addWidget(self.lineEditDidItEverWork)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_6.addWidget(self.label_22)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 133, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButtonNaWhenDidItStop = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaWhenDidItStop.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaWhenDidItStop.setFont(font)
        self.pushButtonNaWhenDidItStop.setObjectName(_fromUtf8("pushButtonNaWhenDidItStop"))
        self.horizontalLayout_6.addWidget(self.pushButtonNaWhenDidItStop)
        self.lineEditWhenDidItStop = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditWhenDidItStop.setFont(font)
        self.lineEditWhenDidItStop.setObjectName(_fromUtf8("lineEditWhenDidItStop"))
        self.horizontalLayout_6.addWidget(self.lineEditWhenDidItStop)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_6.addWidget(self.label_29)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButtonNaChangesMade = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaChangesMade.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaChangesMade.setFont(font)
        self.pushButtonNaChangesMade.setObjectName(_fromUtf8("pushButtonNaChangesMade"))
        self.horizontalLayout_7.addWidget(self.pushButtonNaChangesMade)
        self.lineEditChangesMade = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditChangesMade.sizePolicy().hasHeightForWidth())
        self.lineEditChangesMade.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditChangesMade.setFont(font)
        self.lineEditChangesMade.setObjectName(_fromUtf8("lineEditChangesMade"))
        self.horizontalLayout_7.addWidget(self.lineEditChangesMade)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButtonNaHowManyTermLocation = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaHowManyTermLocation.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaHowManyTermLocation.setFont(font)
        self.pushButtonNaHowManyTermLocation.setObjectName(_fromUtf8("pushButtonNaHowManyTermLocation"))
        self.horizontalLayout_8.addWidget(self.pushButtonNaHowManyTermLocation)
        self.lineEditHowManyTermLocation = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditHowManyTermLocation.setFont(font)
        self.lineEditHowManyTermLocation.setObjectName(_fromUtf8("lineEditHowManyTermLocation"))
        self.horizontalLayout_8.addWidget(self.lineEditHowManyTermLocation)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_6.addWidget(self.label_27)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonNaHowManyTermDown = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaHowManyTermDown.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaHowManyTermDown.setFont(font)
        self.pushButtonNaHowManyTermDown.setObjectName(_fromUtf8("pushButtonNaHowManyTermDown"))
        self.horizontalLayout_9.addWidget(self.pushButtonNaHowManyTermDown)
        self.lineEditHowManyTermDown = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditHowManyTermDown.setFont(font)
        self.lineEditHowManyTermDown.setObjectName(_fromUtf8("lineEditHowManyTermDown"))
        self.horizontalLayout_9.addWidget(self.lineEditHowManyTermDown)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.AutoText)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_6.addWidget(self.label_26)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pushButtonNaAnyAffected = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaAnyAffected.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaAnyAffected.setFont(font)
        self.pushButtonNaAnyAffected.setObjectName(_fromUtf8("pushButtonNaAnyAffected"))
        self.horizontalLayout_11.addWidget(self.pushButtonNaAnyAffected)
        self.lineEditAnyAffected = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAnyAffected.setFont(font)
        self.lineEditAnyAffected.setObjectName(_fromUtf8("lineEditAnyAffected"))
        self.horizontalLayout_11.addWidget(self.lineEditAnyAffected)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_6.addWidget(self.label_23)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.pushButtonNaScreenshotsAttached = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaScreenshotsAttached.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaScreenshotsAttached.setFont(font)
        self.pushButtonNaScreenshotsAttached.setObjectName(_fromUtf8("pushButtonNaScreenshotsAttached"))
        self.horizontalLayout_12.addWidget(self.pushButtonNaScreenshotsAttached)
        self.lineEditScreenshotsAttached = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditScreenshotsAttached.setFont(font)
        self.lineEditScreenshotsAttached.setObjectName(_fromUtf8("lineEditScreenshotsAttached"))
        self.horizontalLayout_12.addWidget(self.lineEditScreenshotsAttached)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_6.addWidget(self.label_21)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButtonNaModelSerial = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaModelSerial.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaModelSerial.setFont(font)
        self.pushButtonNaModelSerial.setObjectName(_fromUtf8("pushButtonNaModelSerial"))
        self.horizontalLayout_13.addWidget(self.pushButtonNaModelSerial)
        self.lineEditModelSerial = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditModelSerial.setFont(font)
        self.lineEditModelSerial.setObjectName(_fromUtf8("lineEditModelSerial"))
        self.horizontalLayout_13.addWidget(self.lineEditModelSerial)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_6.addWidget(self.label_24)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 133, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButtonNaAlternativeMethod = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaAlternativeMethod.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaAlternativeMethod.setFont(font)
        self.pushButtonNaAlternativeMethod.setObjectName(_fromUtf8("pushButtonNaAlternativeMethod"))
        self.horizontalLayout_14.addWidget(self.pushButtonNaAlternativeMethod)
        self.lineEditAlternativeMethod = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditAlternativeMethod.setFont(font)
        self.lineEditAlternativeMethod.setObjectName(_fromUtf8("lineEditAlternativeMethod"))
        self.horizontalLayout_14.addWidget(self.lineEditAlternativeMethod)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_6.addWidget(self.label_25)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, -1, 133, -1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plainTextEditNextSteps = QtGui.QPlainTextEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditNextSteps.sizePolicy().hasHeightForWidth())
        self.plainTextEditNextSteps.setSizePolicy(sizePolicy)
        self.plainTextEditNextSteps.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEditNextSteps.setFont(font)
        self.plainTextEditNextSteps.setObjectName(_fromUtf8("plainTextEditNextSteps"))
        self.gridLayout_5.addWidget(self.plainTextEditNextSteps, 0, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButtonNaNextSteps = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButtonNaNextSteps.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNaNextSteps.setFont(font)
        self.pushButtonNaNextSteps.setObjectName(_fromUtf8("pushButtonNaNextSteps"))
        self.verticalLayout_5.addWidget(self.pushButtonNaNextSteps)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.plainTextEditDescriptionProblem = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditDescriptionProblem.sizePolicy().hasHeightForWidth())
        self.plainTextEditDescriptionProblem.setSizePolicy(sizePolicy)
        self.plainTextEditDescriptionProblem.setMinimumSize(QtCore.QSize(350, 50))
        self.plainTextEditDescriptionProblem.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEditDescriptionProblem.setFont(font)
        self.plainTextEditDescriptionProblem.setObjectName(_fromUtf8("plainTextEditDescriptionProblem"))
        self.verticalLayout.addWidget(self.plainTextEditDescriptionProblem)
        spacerItem5 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.plainTextEditReporoductionTroubleshooting = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditReporoductionTroubleshooting.sizePolicy().hasHeightForWidth())
        self.plainTextEditReporoductionTroubleshooting.setSizePolicy(sizePolicy)
        self.plainTextEditReporoductionTroubleshooting.setMinimumSize(QtCore.QSize(350, 250))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEditReporoductionTroubleshooting.setFont(font)
        self.plainTextEditReporoductionTroubleshooting.setObjectName(_fromUtf8("plainTextEditReporoductionTroubleshooting"))
        self.verticalLayout.addWidget(self.plainTextEditReporoductionTroubleshooting)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 10, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_8.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_8.setText(_fromUtf8(""))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 2, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_6.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 4, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_3.setText(_fromUtf8(""))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_7.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 2, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_5.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_4.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 15, -1, 15)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, 10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditIncident = QtGui.QLineEdit(self.centralwidget)
        self.lineEditIncident.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditIncident.sizePolicy().hasHeightForWidth())
        self.lineEditIncident.setSizePolicy(sizePolicy)
        self.lineEditIncident.setMaximumSize(QtCore.QSize(257, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditIncident.setFont(font)
        self.lineEditIncident.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditIncident.setText(_fromUtf8(""))
        self.lineEditIncident.setFrame(True)
        self.lineEditIncident.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEditIncident.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditIncident.setPlaceholderText(_fromUtf8("#Incident number"))
        self.lineEditIncident.setObjectName(_fromUtf8("lineEditIncident"))
        self.horizontalLayout_4.addWidget(self.lineEditIncident)
        spacerItem8 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.comboBoxSeverity = QtGui.QComboBox(self.centralwidget)
        self.comboBoxSeverity.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxSeverity.setFont(font)
        self.comboBoxSeverity.setAcceptDrops(False)
        self.comboBoxSeverity.setStatusTip(_fromUtf8(""))
        self.comboBoxSeverity.setWhatsThis(_fromUtf8(""))
        self.comboBoxSeverity.setAccessibleName(_fromUtf8(""))
        self.comboBoxSeverity.setEditable(False)
        self.comboBoxSeverity.setFrame(True)
        self.comboBoxSeverity.setObjectName(_fromUtf8("comboBoxSeverity"))
        self.comboBoxSeverity.addItem(_fromUtf8(""))
        self.comboBoxSeverity.addItem(_fromUtf8(""))
        self.comboBoxSeverity.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBoxSeverity)
        self.comboBoxStatus = QtGui.QComboBox(self.centralwidget)
        self.comboBoxStatus.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxStatus.setFont(font)
        self.comboBoxStatus.setObjectName(_fromUtf8("comboBoxStatus"))
        self.comboBoxStatus.addItem(_fromUtf8(""))
        self.comboBoxStatus.addItem(_fromUtf8(""))
        self.comboBoxStatus.addItem(_fromUtf8(""))
        self.comboBoxStatus.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBoxStatus)
        spacerItem9 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.lineEditDatum = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditDatum.sizePolicy().hasHeightForWidth())
        self.lineEditDatum.setSizePolicy(sizePolicy)
        self.lineEditDatum.setMinimumSize(QtCore.QSize(123, 0))
        self.lineEditDatum.setMaximumSize(QtCore.QSize(123, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditDatum.setFont(font)
        self.lineEditDatum.setText(_fromUtf8(""))
        self.lineEditDatum.setObjectName(_fromUtf8("lineEditDatum"))
        self.horizontalLayout_4.addWidget(self.lineEditDatum)
        spacerItem10 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButtonSave = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSave.sizePolicy().hasHeightForWidth())
        self.pushButtonSave.setSizePolicy(sizePolicy)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSave.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonSave.setAutoFillBackground(False)
        self.pushButtonSave.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/001-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSave.setIcon(icon5)
        self.pushButtonSave.setIconSize(QtCore.QSize(44, 44))
        self.pushButtonSave.setAutoDefault(False)
        self.pushButtonSave.setDefault(False)
        self.pushButtonSave.setFlat(True)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.horizontalLayout_4.addWidget(self.pushButtonSave)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditImePrezime = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditImePrezime.setFont(font)
        self.lineEditImePrezime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditImePrezime.setObjectName(_fromUtf8("lineEditImePrezime"))
        self.horizontalLayout.addWidget(self.lineEditImePrezime)
        self.lineEditBrojTelefona = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditBrojTelefona.setFont(font)
        self.lineEditBrojTelefona.setObjectName(_fromUtf8("lineEditBrojTelefona"))
        self.horizontalLayout.addWidget(self.lineEditBrojTelefona)
        self.lineEditZipCode = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditZipCode.setFont(font)
        self.lineEditZipCode.setObjectName(_fromUtf8("lineEditZipCode"))
        self.horizontalLayout.addWidget(self.lineEditZipCode)
        self.lineEditSiteKey = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditSiteKey.setFont(font)
        self.lineEditSiteKey.setObjectName(_fromUtf8("lineEditSiteKey"))
        self.horizontalLayout.addWidget(self.lineEditSiteKey)
        self.lineEditEmail = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setObjectName(_fromUtf8("lineEditEmail"))
        self.horizontalLayout.addWidget(self.lineEditEmail)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 967, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTestic = QtGui.QMenu(self.menubar)
        self.menuTestic.setObjectName(_fromUtf8("menuTestic"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSdsa = QtGui.QAction(MainWindow)
        self.actionSdsa.setObjectName(_fromUtf8("actionSdsa"))
        self.actionSadas = QtGui.QAction(MainWindow)
        self.actionSadas.setObjectName(_fromUtf8("actionSadas"))
        self.actionSda = QtGui.QAction(MainWindow)
        self.actionSda.setObjectName(_fromUtf8("actionSda"))
        self.actionAsd = QtGui.QAction(MainWindow)
        self.actionAsd.setObjectName(_fromUtf8("actionAsd"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setWhatsThis(_fromUtf8(""))
        self.actionAbout.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionTestic = QtGui.QAction(MainWindow)
        self.actionTestic.setObjectName(_fromUtf8("actionTestic"))
        self.menuHelp.addAction(self.actionAbout)
        self.menuTestic.addAction(self.actionTestic)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuTestic.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditImePrezime, self.lineEditBrojTelefona)
        MainWindow.setTabOrder(self.lineEditBrojTelefona, self.lineEditZipCode)
        MainWindow.setTabOrder(self.lineEditZipCode, self.lineEditSiteKey)
        MainWindow.setTabOrder(self.lineEditSiteKey, self.lineEditEmail)
        MainWindow.setTabOrder(self.lineEditEmail, self.plainTextEditDescriptionProblem)
        MainWindow.setTabOrder(self.plainTextEditDescriptionProblem, self.plainTextEditReporoductionTroubleshooting)
        MainWindow.setTabOrder(self.plainTextEditReporoductionTroubleshooting, self.lineEditHasSiteEverCalled)
        MainWindow.setTabOrder(self.lineEditHasSiteEverCalled, self.pushButtonNaDidItEverWork)
        MainWindow.setTabOrder(self.pushButtonNaDidItEverWork, self.lineEditDidItEverWork)
        MainWindow.setTabOrder(self.lineEditDidItEverWork, self.pushButtonNaWhenDidItStop)
        MainWindow.setTabOrder(self.pushButtonNaWhenDidItStop, self.lineEditWhenDidItStop)
        MainWindow.setTabOrder(self.lineEditWhenDidItStop, self.pushButtonNaChangesMade)
        MainWindow.setTabOrder(self.pushButtonNaChangesMade, self.lineEditChangesMade)
        MainWindow.setTabOrder(self.lineEditChangesMade, self.pushButtonNaHowManyTermLocation)
        MainWindow.setTabOrder(self.pushButtonNaHowManyTermLocation, self.lineEditHowManyTermLocation)
        MainWindow.setTabOrder(self.lineEditHowManyTermLocation, self.pushButtonNaHowManyTermDown)
        MainWindow.setTabOrder(self.pushButtonNaHowManyTermDown, self.lineEditHowManyTermDown)
        MainWindow.setTabOrder(self.lineEditHowManyTermDown, self.pushButtonNaAnyAffected)
        MainWindow.setTabOrder(self.pushButtonNaAnyAffected, self.lineEditAnyAffected)
        MainWindow.setTabOrder(self.lineEditAnyAffected, self.pushButtonNaScreenshotsAttached)
        MainWindow.setTabOrder(self.pushButtonNaScreenshotsAttached, self.lineEditScreenshotsAttached)
        MainWindow.setTabOrder(self.lineEditScreenshotsAttached, self.pushButtonNaModelSerial)
        MainWindow.setTabOrder(self.pushButtonNaModelSerial, self.lineEditModelSerial)
        MainWindow.setTabOrder(self.lineEditModelSerial, self.pushButtonNaAlternativeMethod)
        MainWindow.setTabOrder(self.pushButtonNaAlternativeMethod, self.lineEditAlternativeMethod)
        MainWindow.setTabOrder(self.lineEditAlternativeMethod, self.lineEditIncident)
        MainWindow.setTabOrder(self.lineEditIncident, self.comboBoxSeverity)
        MainWindow.setTabOrder(self.comboBoxSeverity, self.comboBoxStatus)
        MainWindow.setTabOrder(self.comboBoxStatus, self.lineEditDatum)
        MainWindow.setTabOrder(self.lineEditDatum, self.pushButtonSave)
        MainWindow.setTabOrder(self.pushButtonSave, self.pushButtonStart)
        MainWindow.setTabOrder(self.pushButtonStart, self.pushButtonReset)
        MainWindow.setTabOrder(self.pushButtonReset, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButtonClearAllFields)
        MainWindow.setTabOrder(self.pushButtonClearAllFields, self.pushButtonCopyToClipboard)
        MainWindow.setTabOrder(self.pushButtonCopyToClipboard, self.scrollArea)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Agent Tool", None))
        self.pushButtonClearAllFields.setText(_translate("MainWindow", "CLEAR ALL FIELDS", None))
        self.pushButtonCopyToClipboard.setText(_translate("MainWindow", "COPY TO CLIPBOARD", None))
        self.labelTimer.setText(_translate("MainWindow", "00:00:00", None))
        self.pushButtonStart.setText(_translate("MainWindow", "START", None))
        self.pushButtonReset.setText(_translate("MainWindow", "RESET", None))
        self.label_30.setText(_translate("MainWindow", "Versions:", None))
        self.label_19.setText(_translate("MainWindow", "Has site ever called support for the same issue?", None))
        self.lineEditHasSiteEverCalled.setPlaceholderText(_translate("MainWindow", "YES / NO, if YES, give incident #", None))
        self.label_20.setText(_translate("MainWindow", "Did it ever work?", None))
        self.pushButtonNaDidItEverWork.setText(_translate("MainWindow", "N/A", None))
        self.label_22.setText(_translate("MainWindow", "When did it stop working?", None))
        self.pushButtonNaWhenDidItStop.setText(_translate("MainWindow", "N/A", None))
        self.label_29.setText(_translate("MainWindow", "Changes made around that time?", None))
        self.pushButtonNaChangesMade.setText(_translate("MainWindow", "N/A", None))
        self.label_28.setText(_translate("MainWindow", "How many terminals on location?", None))
        self.pushButtonNaHowManyTermLocation.setText(_translate("MainWindow", "N/A", None))
        self.label_27.setText(_translate("MainWindow", "How many terminals are down?", None))
        self.pushButtonNaHowManyTermDown.setText(_translate("MainWindow", "N/A", None))
        self.label_26.setText(_translate("MainWindow", "Are any affected terminals specialty terminals?", None))
        self.pushButtonNaAnyAffected.setText(_translate("MainWindow", "N/A", None))
        self.label_23.setText(_translate("MainWindow", "Screenshots attached (if applicable)", None))
        self.pushButtonNaScreenshotsAttached.setText(_translate("MainWindow", "N/A", None))
        self.label_21.setText(_translate("MainWindow", "Model & S/N (if hardware related)", None))
        self.pushButtonNaModelSerial.setText(_translate("MainWindow", "N/A", None))
        self.label_24.setText(_translate("MainWindow", "Alternative method that will be used by the site", None))
        self.pushButtonNaAlternativeMethod.setText(_translate("MainWindow", "N/A", None))
        self.label_25.setText(_translate("MainWindow", "***Next steps for next contact:", None))
        self.pushButtonNaNextSteps.setText(_translate("MainWindow", "N/A", None))
        self.label.setText(_translate("MainWindow", "Description of the problem", None))
        self.label_2.setText(_translate("MainWindow", "Reporoduction and Troubleshooting stepks taken to resolve", None))
        self.comboBoxSeverity.setToolTip(_translate("MainWindow", "Severity", None))
        self.comboBoxSeverity.setItemText(0, _translate("MainWindow", "Sev 1", None))
        self.comboBoxSeverity.setItemText(1, _translate("MainWindow", "Sev 2", None))
        self.comboBoxSeverity.setItemText(2, _translate("MainWindow", "Sev 3", None))
        self.comboBoxStatus.setToolTip(_translate("MainWindow", "Status", None))
        self.comboBoxStatus.setItemText(0, _translate("MainWindow", "Open", None))
        self.comboBoxStatus.setItemText(1, _translate("MainWindow", "Closed", None))
        self.comboBoxStatus.setItemText(2, _translate("MainWindow", "WFC", None))
        self.comboBoxStatus.setItemText(3, _translate("MainWindow", "Escalated", None))
        self.label_11.setText(_translate("MainWindow", "Name and last name", None))
        self.label_10.setText(_translate("MainWindow", "Callback number", None))
        self.label_9.setText(_translate("MainWindow", "ZIP code", None))
        self.label_8.setText(_translate("MainWindow", "Site key", None))
        self.label_7.setText(_translate("MainWindow", "Email", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuTestic.setTitle(_translate("MainWindow", "Drugi", None))
        self.actionSdsa.setText(_translate("MainWindow", "sdsa", None))
        self.actionSadas.setText(_translate("MainWindow", "sadas", None))
        self.actionSda.setText(_translate("MainWindow", "sda", None))
        self.actionAsd.setText(_translate("MainWindow", "asd", None))
        self.actionAbout.setText(_translate("MainWindow", "About Lesa", None))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About dude Lesa", None))
        self.actionTestic.setText(_translate("MainWindow", "Testic", None))

import xx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

