# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_glavni.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(936, 838)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../Desktop/saki.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 15, -1, 15)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, 10)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEdit_incident = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_incident.sizePolicy().hasHeightForWidth())
        self.lineEdit_incident.setSizePolicy(sizePolicy)
        self.lineEdit_incident.setMaximumSize(QtCore.QSize(257, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_incident.setFont(font)
        self.lineEdit_incident.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_incident.setText(_fromUtf8(""))
        self.lineEdit_incident.setFrame(True)
        self.lineEdit_incident.setEchoMode(QtGui.QLineEdit.Normal)
        self.lineEdit_incident.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_incident.setPlaceholderText(_fromUtf8("#Incident number"))
        self.lineEdit_incident.setProperty("clearButtonEnabled", False)
        self.lineEdit_incident.setObjectName(_fromUtf8("lineEdit_incident"))
        self.horizontalLayout_4.addWidget(self.lineEdit_incident)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBox_severity = QtGui.QComboBox(self.centralwidget)
        self.comboBox_severity.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_severity.setFont(font)
        self.comboBox_severity.setAcceptDrops(False)
        self.comboBox_severity.setStatusTip(_fromUtf8(""))
        self.comboBox_severity.setWhatsThis(_fromUtf8(""))
        self.comboBox_severity.setAccessibleName(_fromUtf8(""))
        self.comboBox_severity.setEditable(False)
        self.comboBox_severity.setFrame(True)
        self.comboBox_severity.setObjectName(_fromUtf8("comboBox_severity"))
        self.comboBox_severity.addItem(_fromUtf8(""))
        self.comboBox_severity.addItem(_fromUtf8(""))
        self.comboBox_severity.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_severity)
        self.comboBox_status = QtGui.QComboBox(self.centralwidget)
        self.comboBox_status.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_status.setFont(font)
        self.comboBox_status.setObjectName(_fromUtf8("comboBox_status"))
        self.comboBox_status.addItem(_fromUtf8(""))
        self.comboBox_status.addItem(_fromUtf8(""))
        self.comboBox_status.addItem(_fromUtf8(""))
        self.comboBox_status.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_status)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.lineEdit_datum = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_datum.sizePolicy().hasHeightForWidth())
        self.lineEdit_datum.setSizePolicy(sizePolicy)
        self.lineEdit_datum.setMinimumSize(QtCore.QSize(123, 0))
        self.lineEdit_datum.setMaximumSize(QtCore.QSize(123, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_datum.setFont(font)
        self.lineEdit_datum.setText(_fromUtf8(""))
        self.lineEdit_datum.setObjectName(_fromUtf8("lineEdit_datum"))
        self.horizontalLayout_4.addWidget(self.lineEdit_datum)
        spacerItem2 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_save = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_save.setAutoFillBackground(False)
        self.pushButton_save.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/001-save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon1)
        self.pushButton_save.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setDefault(False)
        self.pushButton_save.setFlat(True)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.horizontalLayout_4.addWidget(self.pushButton_save)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_ime_prezime = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ime_prezime.setFont(font)
        self.lineEdit_ime_prezime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_ime_prezime.setObjectName(_fromUtf8("lineEdit_ime_prezime"))
        self.horizontalLayout.addWidget(self.lineEdit_ime_prezime)
        self.lineEdit_broj_telefona = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_broj_telefona.setFont(font)
        self.lineEdit_broj_telefona.setObjectName(_fromUtf8("lineEdit_broj_telefona"))
        self.horizontalLayout.addWidget(self.lineEdit_broj_telefona)
        self.lineEdit_zip_code = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_zip_code.setFont(font)
        self.lineEdit_zip_code.setObjectName(_fromUtf8("lineEdit_zip_code"))
        self.horizontalLayout.addWidget(self.lineEdit_zip_code)
        self.lineEdit_site_key = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_site_key.setFont(font)
        self.lineEdit_site_key.setObjectName(_fromUtf8("lineEdit_site_key"))
        self.horizontalLayout.addWidget(self.lineEdit_site_key)
        self.lineEdit_email = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setObjectName(_fromUtf8("lineEdit_email"))
        self.horizontalLayout.addWidget(self.lineEdit_email)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        spacerItem3 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.pushButton_11 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout_10.addWidget(self.pushButton_11)
        spacerItem4 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout_10.addWidget(self.pushButton_10)
        spacerItem5 = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 2, 1, 1, 2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_timer = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_timer.setFont(font)
        self.label_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer.setObjectName(_fromUtf8("label_timer"))
        self.gridLayout_2.addWidget(self.label_timer, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_start = QtGui.QPushButton(self.centralwidget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/002-play-button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/001-pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_start.setIcon(icon2)
        self.pushButton_start.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_start.setCheckable(True)
        self.pushButton_start.setChecked(False)
        self.pushButton_start.setAutoRepeat(False)
        self.pushButton_start.setAutoExclusive(False)
        self.pushButton_start.setAutoDefault(False)
        self.pushButton_start.setDefault(False)
        self.pushButton_start.setFlat(True)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout_3.addWidget(self.pushButton_start)
        self.pushButton_reset = QtGui.QPushButton(self.centralwidget)
        self.pushButton_reset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_reset.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/prva/images/001-replay.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reset.setIcon(icon3)
        self.pushButton_reset.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_reset.setCheckable(False)
        self.pushButton_reset.setAutoDefault(True)
        self.pushButton_reset.setDefault(False)
        self.pushButton_reset.setFlat(True)
        self.pushButton_reset.setObjectName(_fromUtf8("pushButton_reset"))
        self.horizontalLayout_3.addWidget(self.pushButton_reset)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(330, 16777215))
        self.scrollArea.setFrameShape(QtGui.QFrame.Box)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 2123, 778))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_5.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_5.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(4, 2, 294, 770))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(15, 15, 5, 5)
        self.verticalLayout_6.setSpacing(8)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_19 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_6.addWidget(self.label_19)
        self.lineEdit_has_site_ever_called = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_has_site_ever_called.setFont(font)
        self.lineEdit_has_site_ever_called.setObjectName(_fromUtf8("lineEdit_has_site_ever_called"))
        self.verticalLayout_6.addWidget(self.lineEdit_has_site_ever_called)
        self.label_20 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_6.addWidget(self.label_20)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_na_did_it_ever_work = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_did_it_ever_work.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_did_it_ever_work.setFont(font)
        self.pushButton_na_did_it_ever_work.setObjectName(_fromUtf8("pushButton_na_did_it_ever_work"))
        self.horizontalLayout_5.addWidget(self.pushButton_na_did_it_ever_work)
        self.lineEdit_did_it_ever_work = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_did_it_ever_work.setFont(font)
        self.lineEdit_did_it_ever_work.setObjectName(_fromUtf8("lineEdit_did_it_ever_work"))
        self.horizontalLayout_5.addWidget(self.lineEdit_did_it_ever_work)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_22 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_6.addWidget(self.label_22)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_na_when_did_it_stop = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_when_did_it_stop.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_when_did_it_stop.setFont(font)
        self.pushButton_na_when_did_it_stop.setObjectName(_fromUtf8("pushButton_na_when_did_it_stop"))
        self.horizontalLayout_6.addWidget(self.pushButton_na_when_did_it_stop)
        self.lineEdit_when_did_it_stop = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_when_did_it_stop.setFont(font)
        self.lineEdit_when_did_it_stop.setObjectName(_fromUtf8("lineEdit_when_did_it_stop"))
        self.horizontalLayout_6.addWidget(self.lineEdit_when_did_it_stop)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label_29 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_6.addWidget(self.label_29)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_na_changes_made = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_changes_made.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_changes_made.setFont(font)
        self.pushButton_na_changes_made.setObjectName(_fromUtf8("pushButton_na_changes_made"))
        self.horizontalLayout_7.addWidget(self.pushButton_na_changes_made)
        self.lineEdit_changes_made = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_changes_made.setFont(font)
        self.lineEdit_changes_made.setObjectName(_fromUtf8("lineEdit_changes_made"))
        self.horizontalLayout_7.addWidget(self.lineEdit_changes_made)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.label_28 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_6.addWidget(self.label_28)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.pushButton_na_how_many_term_location = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_how_many_term_location.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_how_many_term_location.setFont(font)
        self.pushButton_na_how_many_term_location.setObjectName(_fromUtf8("pushButton_na_how_many_term_location"))
        self.horizontalLayout_8.addWidget(self.pushButton_na_how_many_term_location)
        self.lineEdit_how_many_term_location = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_how_many_term_location.setFont(font)
        self.lineEdit_how_many_term_location.setObjectName(_fromUtf8("lineEdit_how_many_term_location"))
        self.horizontalLayout_8.addWidget(self.lineEdit_how_many_term_location)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.label_27 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_6.addWidget(self.label_27)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_na_how_many_term_down = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_how_many_term_down.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_how_many_term_down.setFont(font)
        self.pushButton_na_how_many_term_down.setObjectName(_fromUtf8("pushButton_na_how_many_term_down"))
        self.horizontalLayout_9.addWidget(self.pushButton_na_how_many_term_down)
        self.lineEdit_how_many_term_down = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_how_many_term_down.setFont(font)
        self.lineEdit_how_many_term_down.setObjectName(_fromUtf8("lineEdit_how_many_term_down"))
        self.horizontalLayout_9.addWidget(self.lineEdit_how_many_term_down)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.label_26 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.AutoText)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_6.addWidget(self.label_26)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.pushButton_na_any_affected = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_any_affected.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_any_affected.setFont(font)
        self.pushButton_na_any_affected.setObjectName(_fromUtf8("pushButton_na_any_affected"))
        self.horizontalLayout_11.addWidget(self.pushButton_na_any_affected)
        self.lineEdit_any_affected = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_any_affected.setFont(font)
        self.lineEdit_any_affected.setObjectName(_fromUtf8("lineEdit_any_affected"))
        self.horizontalLayout_11.addWidget(self.lineEdit_any_affected)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.label_23 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_6.addWidget(self.label_23)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.pushButton_na_screenshots_attached = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_screenshots_attached.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_screenshots_attached.setFont(font)
        self.pushButton_na_screenshots_attached.setObjectName(_fromUtf8("pushButton_na_screenshots_attached"))
        self.horizontalLayout_12.addWidget(self.pushButton_na_screenshots_attached)
        self.lineEdit_screenshots_attached = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_screenshots_attached.setFont(font)
        self.lineEdit_screenshots_attached.setObjectName(_fromUtf8("lineEdit_screenshots_attached"))
        self.horizontalLayout_12.addWidget(self.lineEdit_screenshots_attached)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.label_21 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_6.addWidget(self.label_21)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.pushButton_na_model_serial = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_model_serial.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_model_serial.setFont(font)
        self.pushButton_na_model_serial.setObjectName(_fromUtf8("pushButton_na_model_serial"))
        self.horizontalLayout_13.addWidget(self.pushButton_na_model_serial)
        self.lineEdit_model_serial = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_model_serial.setFont(font)
        self.lineEdit_model_serial.setObjectName(_fromUtf8("lineEdit_model_serial"))
        self.horizontalLayout_13.addWidget(self.lineEdit_model_serial)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.label_24 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_6.addWidget(self.label_24)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.pushButton_na_alternative_method = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_na_alternative_method.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_na_alternative_method.setFont(font)
        self.pushButton_na_alternative_method.setObjectName(_fromUtf8("pushButton_na_alternative_method"))
        self.horizontalLayout_14.addWidget(self.pushButton_na_alternative_method)
        self.lineEdit_alternative_method = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_alternative_method.setFont(font)
        self.lineEdit_alternative_method.setObjectName(_fromUtf8("lineEdit_alternative_method"))
        self.horizontalLayout_14.addWidget(self.lineEdit_alternative_method)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.label_25 = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_6.addWidget(self.label_25)
        self.plainTextEdit_next_steps = QtGui.QPlainTextEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_next_steps.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_next_steps.setSizePolicy(sizePolicy)
        self.plainTextEdit_next_steps.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_next_steps.setFont(font)
        self.plainTextEdit_next_steps.setObjectName(_fromUtf8("plainTextEdit_next_steps"))
        self.verticalLayout_6.addWidget(self.plainTextEdit_next_steps)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 10, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_8.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 2, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_6.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 4, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_3.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_7.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 2, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_5.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton_4.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 100))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 16777215))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(10)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.textEdit_description_problem = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_description_problem.sizePolicy().hasHeightForWidth())
        self.textEdit_description_problem.setSizePolicy(sizePolicy)
        self.textEdit_description_problem.setMinimumSize(QtCore.QSize(350, 50))
        self.textEdit_description_problem.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textEdit_description_problem.setObjectName(_fromUtf8("textEdit_description_problem"))
        self.verticalLayout.addWidget(self.textEdit_description_problem)
        spacerItem8 = QtGui.QSpacerItem(20, 50, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem8)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.textEdit_reporoduction_troubleshooting = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_reporoduction_troubleshooting.sizePolicy().hasHeightForWidth())
        self.textEdit_reporoduction_troubleshooting.setSizePolicy(sizePolicy)
        self.textEdit_reporoduction_troubleshooting.setMinimumSize(QtCore.QSize(350, 250))
        self.textEdit_reporoduction_troubleshooting.setObjectName(_fromUtf8("textEdit_reporoduction_troubleshooting"))
        self.verticalLayout.addWidget(self.textEdit_reporoduction_troubleshooting)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTestic = QtGui.QMenu(self.menubar)
        self.menuTestic.setObjectName(_fromUtf8("menuTestic"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSdsa = QtGui.QAction(MainWindow)
        self.actionSdsa.setObjectName(_fromUtf8("actionSdsa"))
        self.actionSadas = QtGui.QAction(MainWindow)
        self.actionSadas.setObjectName(_fromUtf8("actionSadas"))
        self.actionSda = QtGui.QAction(MainWindow)
        self.actionSda.setObjectName(_fromUtf8("actionSda"))
        self.actionAsd = QtGui.QAction(MainWindow)
        self.actionAsd.setObjectName(_fromUtf8("actionAsd"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setWhatsThis(_fromUtf8(""))
        self.actionAbout.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionTestic = QtGui.QAction(MainWindow)
        self.actionTestic.setObjectName(_fromUtf8("actionTestic"))
        self.menuHelp.addAction(self.actionAbout)
        self.menuTestic.addAction(self.actionTestic)
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuTestic.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_ime_prezime, self.lineEdit_broj_telefona)
        MainWindow.setTabOrder(self.lineEdit_broj_telefona, self.lineEdit_zip_code)
        MainWindow.setTabOrder(self.lineEdit_zip_code, self.lineEdit_site_key)
        MainWindow.setTabOrder(self.lineEdit_site_key, self.lineEdit_email)
        MainWindow.setTabOrder(self.lineEdit_email, self.textEdit_description_problem)
        MainWindow.setTabOrder(self.textEdit_description_problem, self.textEdit_reporoduction_troubleshooting)
        MainWindow.setTabOrder(self.textEdit_reporoduction_troubleshooting, self.lineEdit_has_site_ever_called)
        MainWindow.setTabOrder(self.lineEdit_has_site_ever_called, self.pushButton_na_did_it_ever_work)
        MainWindow.setTabOrder(self.pushButton_na_did_it_ever_work, self.lineEdit_did_it_ever_work)
        MainWindow.setTabOrder(self.lineEdit_did_it_ever_work, self.pushButton_na_when_did_it_stop)
        MainWindow.setTabOrder(self.pushButton_na_when_did_it_stop, self.lineEdit_when_did_it_stop)
        MainWindow.setTabOrder(self.lineEdit_when_did_it_stop, self.pushButton_na_changes_made)
        MainWindow.setTabOrder(self.pushButton_na_changes_made, self.lineEdit_changes_made)
        MainWindow.setTabOrder(self.lineEdit_changes_made, self.pushButton_na_how_many_term_location)
        MainWindow.setTabOrder(self.pushButton_na_how_many_term_location, self.lineEdit_how_many_term_location)
        MainWindow.setTabOrder(self.lineEdit_how_many_term_location, self.pushButton_na_how_many_term_down)
        MainWindow.setTabOrder(self.pushButton_na_how_many_term_down, self.lineEdit_how_many_term_down)
        MainWindow.setTabOrder(self.lineEdit_how_many_term_down, self.pushButton_na_any_affected)
        MainWindow.setTabOrder(self.pushButton_na_any_affected, self.lineEdit_any_affected)
        MainWindow.setTabOrder(self.lineEdit_any_affected, self.pushButton_na_screenshots_attached)
        MainWindow.setTabOrder(self.pushButton_na_screenshots_attached, self.lineEdit_screenshots_attached)
        MainWindow.setTabOrder(self.lineEdit_screenshots_attached, self.pushButton_na_model_serial)
        MainWindow.setTabOrder(self.pushButton_na_model_serial, self.lineEdit_model_serial)
        MainWindow.setTabOrder(self.lineEdit_model_serial, self.pushButton_na_alternative_method)
        MainWindow.setTabOrder(self.pushButton_na_alternative_method, self.lineEdit_alternative_method)
        MainWindow.setTabOrder(self.lineEdit_alternative_method, self.plainTextEdit_next_steps)
        MainWindow.setTabOrder(self.plainTextEdit_next_steps, self.lineEdit_incident)
        MainWindow.setTabOrder(self.lineEdit_incident, self.comboBox_severity)
        MainWindow.setTabOrder(self.comboBox_severity, self.comboBox_status)
        MainWindow.setTabOrder(self.comboBox_status, self.lineEdit_datum)
        MainWindow.setTabOrder(self.lineEdit_datum, self.pushButton_save)
        MainWindow.setTabOrder(self.pushButton_save, self.pushButton_start)
        MainWindow.setTabOrder(self.pushButton_start, self.pushButton_reset)
        MainWindow.setTabOrder(self.pushButton_reset, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.scrollArea)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lesa", None))
        self.comboBox_severity.setToolTip(_translate("MainWindow", "Severity", None))
        self.comboBox_severity.setItemText(0, _translate("MainWindow", "Sev 1", None))
        self.comboBox_severity.setItemText(1, _translate("MainWindow", "Sev 2", None))
        self.comboBox_severity.setItemText(2, _translate("MainWindow", "Sev 3", None))
        self.comboBox_status.setToolTip(_translate("MainWindow", "Status", None))
        self.comboBox_status.setItemText(0, _translate("MainWindow", "Open", None))
        self.comboBox_status.setItemText(1, _translate("MainWindow", "Closed", None))
        self.comboBox_status.setItemText(2, _translate("MainWindow", "WFC", None))
        self.comboBox_status.setItemText(3, _translate("MainWindow", "Escalated", None))
        self.label_11.setText(_translate("MainWindow", "Name and last name", None))
        self.label_10.setText(_translate("MainWindow", "Callback number", None))
        self.label_9.setText(_translate("MainWindow", "ZIP code", None))
        self.label_8.setText(_translate("MainWindow", "Site key", None))
        self.label_7.setText(_translate("MainWindow", "Email", None))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton", None))
        self.label_timer.setText(_translate("MainWindow", "0:0:0", None))
        self.pushButton_start.setText(_translate("MainWindow", "START", None))
        self.pushButton_reset.setText(_translate("MainWindow", "RESET", None))
        self.label_19.setText(_translate("MainWindow", "Has site ever called support for the same issue?", None))
        self.lineEdit_has_site_ever_called.setPlaceholderText(_translate("MainWindow", "YES / NO, if YES, give incident #", None))
        self.label_20.setText(_translate("MainWindow", "Did it ever work?", None))
        self.pushButton_na_did_it_ever_work.setText(_translate("MainWindow", "N / A", None))
        self.label_22.setText(_translate("MainWindow", "When did it stop working?", None))
        self.pushButton_na_when_did_it_stop.setText(_translate("MainWindow", "N / A", None))
        self.label_29.setText(_translate("MainWindow", "Changes made around that time?", None))
        self.pushButton_na_changes_made.setText(_translate("MainWindow", "N / A", None))
        self.label_28.setText(_translate("MainWindow", "How many terminals on location?", None))
        self.pushButton_na_how_many_term_location.setText(_translate("MainWindow", "N / A", None))
        self.label_27.setText(_translate("MainWindow", "How many terminals are down?", None))
        self.pushButton_na_how_many_term_down.setText(_translate("MainWindow", "N / A", None))
        self.label_26.setText(_translate("MainWindow", "Are any affected terminals specialty terminals?", None))
        self.pushButton_na_any_affected.setText(_translate("MainWindow", "N / A", None))
        self.label_23.setText(_translate("MainWindow", "Screenshots attached (if applicable)", None))
        self.pushButton_na_screenshots_attached.setText(_translate("MainWindow", "N / A", None))
        self.label_21.setText(_translate("MainWindow", "Model & S/N (if hardware related)", None))
        self.pushButton_na_model_serial.setText(_translate("MainWindow", "N / A", None))
        self.label_24.setText(_translate("MainWindow", "Alternative method that will be used by the site", None))
        self.pushButton_na_alternative_method.setText(_translate("MainWindow", "N / A", None))
        self.label_25.setText(_translate("MainWindow", "***Next steps for next contact:", None))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.label.setText(_translate("MainWindow", "Description of the problem", None))
        self.label_2.setText(_translate("MainWindow", "Reporoduction and Troubleshooting stepks taken to resolve", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuTestic.setTitle(_translate("MainWindow", "Drugi", None))
        self.actionSdsa.setText(_translate("MainWindow", "sdsa", None))
        self.actionSadas.setText(_translate("MainWindow", "sadas", None))
        self.actionSda.setText(_translate("MainWindow", "sda", None))
        self.actionAsd.setText(_translate("MainWindow", "asd", None))
        self.actionAbout.setText(_translate("MainWindow", "About Lesa", None))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About dude Lesa", None))
        self.actionTestic.setText(_translate("MainWindow", "Testic", None))

import xx_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

